### ISSUE TITLE
No `GH_DEPLOY_KEY` provided; it must be set.

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/unece-cefact-recommendation-42#9]
- https://github.com/metanorma/unece-cefact-recommendation-42/runs/450298087

**Comment by CAMOBAP** [comment]
@ronaldtse please help with this

**Comment by ronaldtse** [comment]
@CAMOBAP795 I want to move this into mn-samples-un . Once it's moved, let's get rid of this repo?

**Comment by CAMOBAP** [comment]
@ronaldtse no objections, closing this one
